title: DeepPheWAS
description: An R package for performing phenome wide association studies
theme: just-the-docs

url: https://richard-packer.github.io/DeepPheWAS/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
