#! /usr/bin/env Rscript
'
Takes the created phenotypes and filters for case number and optionally for relatedness. Can filter the whole sample or perform filtering by group. These groups are classically ancestries produces a list for each grouping. Can also create sex specific phenotypes (1 each for male and female), these can be selected in subsequent scripts if not wanting all sex_split phenotypes. At each filtering stage will save an R object list containing filtered phenotypes as a list of lists.

All inputs are optional, by default the script will filter for default case numbers in the phenotypes marked for inclusion by the PheWAS_manifest and save the output, edit these default values with quantitative_Case_N and binary_Case_N inputs and use no_case_N_save if not wanting to save the output of the initial case number filtering. If wanting to filter by group use groupings input, if wanting to filter for relatedness then use relate_remove and kinship inputs, to save to none default name use relate_remove_save_name. T add in additional sex specific phenotypes choose the sex_split input alongside the sex_info file and what value male and females are coded in using male and female inputs.

Usage:
    01_phenotype_preparation.R (--phenotype_folder=<FOLDER> | --phenotype_files=<FILES>) (--phenotype_filtered_save_name=<FILE>) [(--relate_remove --kinship_file=<FILE>)] [(--sex_split_phenotypes=<FILE> --sex_info=<FILE>)] [(--age_of_onset_phenotypes=<FILE> --DOB_file=<FILE>)] [--groupings=<FILE> --quantitative_Case_N=<number> --binary_Case_N=<number> --male=<number> --female=<number> --PheWAS_manifest_overide=<FILE> --IVNT --save_RDS=<FILE> --stats_save=<FILE>]

Options:
    -h --help  Show this screen.
    -v --version  Show version.

    Mandatory arguments
    --phenotype_filtered_save_name=<FILE>   Full file path for save location of filtered phenotypes. Saves and dataframe per-group (if provided) that is the
                                            input to the association testing. Name of final save is /path/to/file/(group)_savename.

    --phenotype_folder=<FOLDER>             Full path of the folder containing the phenotype data created in previous steps.
    OR
    --phenotype_files=<FILES>               Comma separated full file paths of phenotype data created in previous steps.


    Optional arguments
    --groupings=<FILE>                      Full path of the file containing group information used for stratifying the sample. If this argument is specified, 
 										    the phenotype filtering will be performed within the groups. Otherwise, the filtering will be performed in all individuals.
    --quantitative_Case_N=<number>          Number that represents the minimum number of cases for quantitative phenotype inclusion.
                                            [default: 100]
    --binary_Case_N=<number>                Number that represents the minimum number of cases for binary phenotype inclusion.
                                            [default: 50]
    --relate_remove                         Specify whether related individuals are additionally excluded (TRUE) or not (FALSE). Default is FALSE.
    --kinship_file=<FILE>                   Full path to the file containing kinship coefficient estimates.

    --sex_split_phenotypes=<FILE>           Full file path to file containing single column labelled PheWAS_ID, containing PheWAS_IDs to make sex specific
                                            phenotypes, will derive and add a male and female version of each phenotype. All sex specific phenotypes
                                            be labelled (PheWAS_ID)_male or (PheWAS_ID)_female.
    --sex_info=<FILE>                       Full path of the combined_sex file (generated by the 02_data_preparation.R script).
    --male=<number>                         Value corresponding to males in the combined_sex file must be a number. [default: 1]
    --female=<number>                       Value corresponding to females in the combined_sex file must be a number. [default: 0]
    --PheWAS_manifest_overide=<FILE>        Full file path of the alternative PheWAS_manifest file.

    --age_of_onset_phenotypes=<FILE>        Full file path to file containing three columns PheWAS_ID,lower_limit,upper_limit,transformation. PheWAS_ID are
                                            the phenotypes to create the age_of_onset phenotypes for, lower_limit is the lower age boundary to filter read
                                            as <=, upper_limit is the upper age boundary acceptable read as >=. Transformation is the type of transformation
                                            (if any) that should be applied to the phenotype. Current accepted transformations are IVNT for inverse normal
                                            transformation. All age of onset phenotypes to be labelled (PheWAS_ID)_age_of_onset.
    --DOB_file=<FILE>                       Full file path to file containing DOB information.
    --IVNT                                  Specify whether quantitative phenotypes, defined in the PheWAS manifest, should undergo a rank-based inverse normal 
										    transformation (TRUE) or not (FALSE). Default is FALSE.
    --save_RDS=<FILE>                       Full file path to save location to save and intermediate RDS file that has been filtererd by case_N and
                                            relatedness (if chosen) but not converted to dataframe for analysis.
    --stats_save=<FILE>                     Full file path to save file for stats, saves summary stats for phenotypes for number of cases and controls in
                                            each grouping variable.File name will be appended with _N_filtered.csv or _relate_remove.csv, depending on
                                            if relate remove was selected.

' -> doc

suppressMessages(library(docopt))

arguments <- docopt(doc, version = 'v1.0 01_phenotype_preparation.R')

library(devtools)
load_all()

phenotype_preparation(phenotype_filtered_save_name=arguments$phenotype_filtered_save_name,
                      phenotype_folder=arguments$phenotype_folder,
                      phenotype_files=arguments$phenotype_files,
                      groupings=arguments$groupings,
                      quantitative_Case_N=arguments$quantitative_Case_N,
                      binary_Case_N=arguments$binary_Case_N,
                      relate_remove=arguments$relate_remove,
                      kinship_file=arguments$kinship_file,
                      sex_split_phenotypes=arguments$sex_split_phenotypes,
                      sex_info=arguments$sex_info,
                      male=arguments$male,
                      female=arguments$female,
                      PheWAS_manifest_overide=arguments$PheWAS_manifest_overide,
                      age_of_onset_phenotypes=arguments$age_of_onset_phenotypes,
                      DOB_file=arguments$DOB_file,
                      IVNT=arguments$IVNT,
                      save_RDS=arguments$save_RDS,
                      stats_save=arguments$stats_save)
