#! /usr/bin/env Rscript
'CThis script concatenates and edits linked healthcare data from UK Biobank into a single long file with participant identifier, clinical code, date of clinical code’s recording, and data source. 
Current data sources are:MD – when ICD-10 code is taken from mortality data; cancer – when ICD-10 code is taken from cancer registry data; ICD10-1 – when an ICD-10 code is taken from hospital records as one of the primary causes of admission; ICD10-2 – when an ICD-10 code is taken from hospital records as a secondary cause of admission; ICD10-3 – when an ICD-10 code is taken from hospital records as an external cause of admission; ICD9-1 – when an ICD-9 code is taken from hospital records as one of the primary causes of admission; ICD9-2 – when an ICD-9 code is taken from hospital records as an external cause of admission; ICD9-3 – when an ICD-9 code is taken from hospital records as one of the primary causes of admission; OPCS – A OPCS-4 code taken from the hospital records; SR – A self-report code for a non-cancer illness taken from data field 20002; SROP - A self-report code for an operation taken from data field 20004; V2 – A Read V2 code taken from the primary care clinical data; V3 – A Read V3 code taken from the primary care clinical data.
The current iteration of this script is purpose-built for UK Biobank data. As such, if this script is to be applied to non-UK Biobank data, it would first need to be formatted to mimic that of UK Biobank or to mimic the expected output of the script. The two self-reported data sources are specific to UK Biobank and if similar data were available in another data set, these would need to be mapped to the UK Biobank code used in data fields 20002 and 20004. 
Primary care prescription data from UK Biobank does not lend itself to be easily combined in this way and so it is edited and saved as a separate file.

Usage:
    02_data_preparation.R (--save_location=<FOLDER>) [--min_data=<FILE> --GPC=<FILE> --GPP=<FILE> --hesin_diag=<FILE> --HESIN=<FILE> --hesin_oper=<FILE> --death_cause=<FILE> --death=<FILE> --exclusions=<FILE> --king_coef=<FILE>]

Options:
    -h --help                 Show this screen.
    -v --version              Show version.

    Mandatory
    --save_location=<FOLDER>  Full file path for the common folder to save created files.

    Options
    --min_data=<FILE>         Full path of the file generated by the previous step (01_minimum_data.R).
    --GPC=<FILE>              Full path of the primary care clinical data from UK Biobank.
    --GPP=<FILE>              Full path of the primary care prescription data from UK Biobank.
    --hesin_diag=<FILE>       Full file path of hesin_diag file from UK-Biobank.
    --HESIN=<FILE>            Full file path of HESIN file from UK-Biobank.
    --hesin_oper=<FILE>       Full file path of the hesin_oper file from UK-Biobank.
    --death_cause=<FILE>      Full file path of the death_cause file from UK-Biobank.
    --death=<FILE>            Full file path of the death file from UK-Biobank contains date of death info.
    --exclusions=<FILE>       Full path of the file containing individuals to be excluded from the analysis. Defaults behaviour is to retain all individuals.
    --king_coef=<FILE>        Full file path of related data file containing King coefficient scores for related ID pairs
                              from UK-Biobank.

' -> doc

suppressMessages(library(docopt))
arguments <- docopt(doc, version = 'v0.2 02_data_preparation.R')

library(devtools)
load_all()

data_preparation_R(min_data=arguments$min_data,
                   GPC=arguments$GPC,
                   GPP=arguments$GPP,
                   hesin_diag=arguments$hesin_diag,
                   HESIN=arguments$HESIN,
                   hesin_oper=arguments$hesin_oper,
                   death_cause=arguments$death_cause,
                   death=arguments$death,
                   exclusions=arguments$exclusions,
                   king_coef=arguments$king_coef,
                   save_location=arguments$save_location)
