#! /usr/bin/env Rscript
'This script creates Data-Field phenotypes from UK Biobank Data-Field IDs and primary care data. The script uses the PheWAS_manifest.csv file (provided with the Platform, located in the data/ folder) as a guide to creating phenotypes and will only create phenotypes where the required Data-Field ID data is available. If data from outside UK Biobank are being used, UK Biobank Data-Field IDs would need to be mapped to their equivalent in the alternative data source.

Usage:
    03b_data_field_phenotypes.R (--min_data=<FILE> --phenotype_save_file=<FILE>) [--N_cores=<number> --PheWAS_manifest_overide=<FILE> --append_file=<FILE>]

Options:
    -h --help                                 Show this screen.
    -v --version                              Show version.

    Mandated inputs
    --min_data=<FILE>                         Full path of the tab-separated file generated by the minimum_data.R script.
    --phenotype_save_file=<FILE>              Full path for the save file for the generated concepts RDS to be used for phenotype creation.

    Options
    --N_cores=<number>                        Number of cores requested if parallel computing is desired. Defaults to single core computing.
    --PheWAS_manifest_overide=<FILE>          Full path of an alternative to the data/PheWAS_manifest.csv file.

    --append_file=<FILE>                      Full path of an existing R object containing Data-Field phenotype information to which additional phenotypes derived by this script will be appended.
' -> doc

suppressMessages(library(docopt))
arguments <- docopt(doc, version = 'v0.2 03b_data_field_phenotypes.R')

library(devtools)
load_all()

data_field_phenotyping(arguments$min_data,
                       arguments$phenotype_save_file,
                       arguments$N_cores,
                       arguments$PheWAS_manifest_overide,
                       arguments$append_file)
