#! /usr/bin/env Rscript
'This script creates formula phenotypes from the phenotype data generated by earlier scripts. The script uses the PheWAS_manifest.csv file (provided with the package) as a guide to creating phenotypes.

Usage:
    04_formula_phenotypes.R (--min_data=<FILE> --phenotype_save_file=<FILE>) [--data_field_phenotypes=<FILE> --sex_info=<FILE> --PheWAS_manifest_overide=<FILE>]

Options:
    -h --help                                 Show this screen.
    -v --version                              Show version.

    Mandated inputs
    --min_data=<FILE>                         Full path of the file generated by the previous step (01_minimum_data.R).
    --phenotype_save_file=<FILE>              Full path of the save file for the generated concepts RDS to be used for phenotype creation.

    Options
    --data_field_phenotypes=<FILE>            Full path of the data_field.RDS file produced by 03b_data_field_phenotypes.R, currently only used for eGFR phenotype.
    --sex_info=<FILE>                         Full file path of the combined_sex file a file containing sex information (0=female,
                                              1=male). Used only for eGFR field_ID phenotype.
    --PheWAS_manifest_overide=<FILE>          Full file path of the alternative PheWAS_manifest file.


' -> doc

suppressMessages(library(docopt))
arguments <- docopt(doc, version = 'v0.2 04_formula_phenotypes.R')

library(devtools)
load_all()

formula_phenotypes(min_data=arguments$min_data,
                   data_field_phenotypes=arguments$data_field_phenotypes,
                   sex_info=arguments$sex_info,
                   PheWAS_manifest_overide=arguments$PheWAS_manifest_overide,
                   phenotype_save_file=arguments$phenotype_save_file)
