#' Creates formula phenotypes.
#' @param min_data Full path of the file generated by the previous step (01_minimum_data.R).
#' @param data_field_phenotypes Full path of the data_field.RDS file produced by 03b_data_field_phenotypes.R, currently only used for eGFR phenotype.
#' @param sex_info Full file path of the combined_sex file a file containing sex information (0=female, 1=male). Used only for eGFR field_ID phenotype.
#' @param PheWAS_manifest_overide Full file path of the alternative PheWAS_manifest file.
#' @param phenotype_save_file Full path of the save file for the generated concepts RDS to be used for phenotype creation.
#' @return A R object containing formula phenotypes.
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export
formula_phenotypes <- function(min_data,
                               data_field_phenotypes,
                               sex_info,
                               PheWAS_manifest_overide,
                               phenotype_save_file){

  # data_field_phenotypes
  if(!is.null(data_field_phenotypes)){
    if(!file.exists(data_field_phenotypes)){
      rlang::abort(paste0("'data_field_phenotypes' must be a file"))
    }
    data_field_phenotypes <- readRDS(data_field_phenotypes)
    current_IDs <- names(data_field_phenotypes)
  } else {
    current_IDs <- c(NA)
  }
  # minimum data
  if(!is.null(min_data)){
    if(!file.exists(min_data)){
      rlang::abort(paste0("'min_data' must be a file"))
    }
    min_data <- data.table::fread(min_data)
    current_field_id <- gsub("-.*", "\\1", colnames(min_data))
  }
  # PheWAS manifest
  if(is.null(PheWAS_manifest_overide)){
    PheWAS_manifest <- data.table::fread(system.file("extdata","PheWAS_manifest.csv.gz", package = "DeepPheWAS"))
  } else {
    if(!file.exists(PheWAS_manifest_overide)){
      rlang::abort(paste0("'PheWAS_manifest_overide' must be a file"))
    }
    PheWAS_manifest <- data.table::fread(PheWAS_manifest_overide)
    PheWAS_manifest_overide_colname <- c("PheWAS_ID","broad_catagory","category","phenotype","range_ID","sex","field_code","QC_flag_ID","QC_filter_values","first_last_max_min_value","date_code","age_code","case_code","control_code","exclude_case_control_crossover","included_in_analysis","quant_combination","primary_care_code_list","limits","lower_limit","upper_limit","transformation","analysis","age_col","pheno_group","short_desc","group_narrow","concept_name","concept_description","Notes")

    if(!all(tibble::has_name(PheWAS_manifest,PheWAS_manifest_overide_colname))){
      warning(paste0("'PheWAS_manifest_overide' does not have the correct colnames and may not produce the correct output, expected colnames are:
                                 '"),paste(PheWAS_manifest_overide_colname, collapse=","),paste0("'
                                 not:
                                 "),paste(colnames(PheWAS_manifest), collapse=","),
              paste0("
                                 differences between inputed file and expected are:
                                 "),paste(setdiff_all(names(PheWAS_manifest),PheWAS_manifest_overide_colname), collapse=","))

    }
  }
  # save location
  phenotype_save_location <- phenotype_save_file
  new_folder <- stringr::str_remove(phenotype_save_file,basename(phenotype_save_file))
  if(!dir.exists(new_folder)){
    dir.create(new_folder)}

  # empty list
  formula_phenotypes <- list()

  # eGFR uses cystatin field ID but a slightly more involved formula so is sectioned off here, will only run if the appropriate
  if ("Q2020" %in% PheWAS_manifest$PheWAS_ID & "Q0513" %in% current_IDs & !is.null(sex_info)) {
    # Subset biomarker data to baseline cystatin-C measure to calculate eGFR taken from here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4398023/
    # sex info
    # 0= female, 1=male
    sex <- data.table::fread(sex_info)
    eGFR <- data_field_phenotypes[c("Q0513")] %>%
      purrr::reduce(dplyr::full_join,by="eid") %>%
      dplyr::rename(cystatin=.data$Q0513,age=.data$Q0513_age) %>%
      dplyr::inner_join(sex) %>%
      tidyr::drop_na(.data$sex,.data$cystatin) %>%
      dplyr::mutate(eGFR=ifelse(.data$cystatin>0.8 & .data$sex==0,
                                (133*(.data$cystatin/0.8)^-1.328*(0.996^.data$age)*0.932),ifelse(
                                  .data$cystatin>0.8 & .data$sex==1,
                                  (133*(.data$cystatin/0.8)^-1.328*(0.996^.data$age)),ifelse(
                                    .data$cystatin<=0.8 & .data$sex==0,
                                    (133*(.data$cystatin/0.8)^-0.499*(0.996^.data$age)*0.932),(133*(.data$cystatin/0.8)^-0.499*(0.996^.data$age)*0.932))))) %>%
      dplyr::select(.data$eid,Q2020=.data$eGFR,.data$earliest_date,Q2020_age=.data$age)
    eGFR_list <- list(Q2020=eGFR)
    formula_phenotypes <- append(formula_phenotypes,eGFR_list)
  }
  ## QTc
  if("21003" %in% current_field_id & "22333" %in% current_field_id & "53" %in% current_field_id & "22331" %in% current_field_id) {
    ## QTc
    age <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^21003-")) %>%
      dplyr::select(1,age=2) %>%
      tidyr::drop_na()
    date <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^53-")) %>%
      dplyr::select(1,earliest_date=2) %>%
      tidyr::drop_na() %>%
      dplyr::mutate(earliest_date=lubridate::ymd(.data$earliest_date))
    QT <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^22331-")) %>%
      dplyr::select(1,QT=2) %>%
      tidyr::drop_na()
    RR <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^22333-")) %>%
      dplyr::select(1,RR=2) %>%
      tidyr::drop_na()
    QTc <- QT %>%
      dplyr::left_join(RR, by="eid") %>%
      dplyr::left_join(age, by="eid") %>%
      dplyr::left_join(date,by = "eid") %>%
      dplyr::mutate(qtc_interval_bazett = .data$QT/sqrt(.data$RR/1000)) %>%
      dplyr::select(.data$eid,Q1500=.data$qtc_interval_bazett,.data$earliest_date,Q1500_age=.data$age)
    QTc_list <- list(Q1500=QTc)
    formula_phenotypes <- append(formula_phenotypes,QTc_list)
  }
  ## WHR
  if("21003" %in% current_field_id & "48" %in% current_field_id & "53" %in% current_field_id & "49" %in% current_field_id){
    ## WHR
    age <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^21003-")) %>%
      dplyr::select(1,age=2) %>%
      tidyr::drop_na()
    date <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^53-")) %>%
      dplyr::select(1,earliest_date=2) %>%
      tidyr::drop_na() %>%
      dplyr::mutate(earliest_date=lubridate::ymd(.data$earliest_date))
    waist <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^48-")) %>%
      dplyr::select(1,waist=2) %>%
      tidyr::drop_na()
    hip <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^49-")) %>%
      dplyr::select(1,hip=2) %>%
      tidyr::drop_na()
    WHR <- waist %>%
      dplyr::left_join(hip,by="eid") %>%
      dplyr::left_join(age, by="eid") %>%
      dplyr::left_join(date,by = "eid") %>%
      dplyr::mutate(WHR=.data$waist / .data$hip) %>%
      dplyr::select(.data$eid,Q0007=.data$WHR,.data$earliest_date,Q0007_age=.data$age)
    WHR_list <- list(Q0007=WHR)
    formula_phenotypes <- append(formula_phenotypes,WHR_list)
  }

  # LF ratio
  if("53" %in% current_field_id & "21003" %in% current_field_id & "3062" %in% current_field_id & "20151" %in% current_field_id & "3063" %in% current_field_id & "20150" %in% current_field_id){
    # need date of assessment
    date_assesment <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^53-"))
    date_cols <- colnames(date_assesment)[-1]
    # and age at assessment
    age_assesment <-  min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^21003-"))
    age_cols <- colnames(age_assesment)[-1]
    # FVC all measure and single best measure
    FVC_all <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^3062-"))
    FVC_best <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^20151-")) %>%
      tidyr::drop_na() %>%
      dplyr::rename(FVC=2)
    # col names used to combine values
    data_field_FVC <- colnames(FVC_all)[-1]
    # find date position for best FVC value
    FVC_mod <- FVC_all %>%
      dplyr::mutate(results_list=purrr::transpose(dplyr::across(tidyselect::all_of(data_field_FVC)))) %>%
      dplyr::left_join(FVC_best) %>%
      tidyr::drop_na(.data$FVC) %>%
      dplyr::mutate(position_best=unlist(purrr::map2(.data$results_list,.data$FVC,~match(.y,unlist(.x)))),
                    matching_date_position_first=(as.numeric(gsub(".*-(.+)\\..*", "\\1", data_field_FVC[.data$position_best])))+1,) %>%
      dplyr::select(.data$eid,.data$FVC,FVC_position=.data$matching_date_position_first)
    # FEV1 all measures and best measure
    FEV1_all <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^3063-"))
    FEV1_best <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^20150-")) %>%
      tidyr::drop_na() %>%
      dplyr::rename(FEV1=2)
    # col names used for combining
    data_field_FEV1 <- colnames(FEV1_all)[-1]
    # finding date/age position
    FEV1_mod <- FEV1_all %>%
      dplyr::mutate(results_list=purrr::transpose(dplyr::across(tidyselect::all_of(data_field_FEV1)))) %>%
      dplyr::left_join(FEV1_best) %>%
      tidyr::drop_na(.data$FEV1) %>%
      dplyr::mutate(position_best=unlist(purrr::map2(.data$results_list,.data$FEV1,~match(.y,unlist(.x)))),
                    matching_date_position_first=(as.numeric(gsub(".*-(.+)\\..*", "\\1", data_field_FEV1[.data$position_best])))+1,) %>%
      dplyr::select(.data$eid,.data$FEV1,FEV1_position=.data$matching_date_position_first)
    # making ratio and finding date and age based on shared position
    ratio <- FEV1_mod %>%
      dplyr::left_join(FVC_mod, by="eid") %>%
      dplyr::mutate(divergence=ifelse(.data$FEV1_position==.data$FVC_position,1,0)) %>%
      dplyr::filter(.data$divergence==1) %>%
      dplyr::mutate(ratio=.data$FEV1/.data$FVC) %>%
      dplyr::select(.data$eid,.data$ratio,position=.data$FEV1_position) %>%
      dplyr::left_join(date_assesment, by="eid") %>%
      dplyr::mutate(dplyr::across(tidyselect::all_of(date_cols), ~gsub(" .*", "", .x))) %>%
      dplyr::mutate(dplyr::across(tidyselect::all_of(date_cols),as.character)) %>%
      dplyr::mutate(date_list = purrr::transpose(dplyr::across(tidyselect::all_of(date_cols))),
                    earliest_date=purrr::map2(.data$date_list,.data$position, function(x,y) x[[y]])) %>%
      dplyr::left_join(age_assesment, by="eid") %>%
      dplyr::mutate(age_list=purrr::transpose(dplyr::across(tidyselect::all_of(age_cols))),
                    pheno_age = unlist(purrr::map2(.data$age_list,.data$position, function(x,y) x[[y]]))) %>%
      dplyr::select(.data$eid,.data$ratio,.data$earliest_date,.data$pheno_age) %>%
      dplyr::mutate(earliest_date=lubridate::ymd(.data$earliest_date)) %>%
      purrr::set_names(c("eid","Q0123","earliest_date","Q0123_age"))
    # make list and append
    ratio_list <- list(Q0123=ratio)
    formula_phenotypes <- append(formula_phenotypes,ratio_list)
  }
  #Chronic multi-site pain
  if("53" %in% current_field_id & "21003" %in% current_field_id & "6159" %in% current_field_id){
    age <- min_data %>%
      dplyr::select("eid",tidyselect::matches("^21003-")) %>%
      dplyr::select(1,age=2) %>%
      tidyr::drop_na()
    date <- min_data %>%
      dplyr::select("eid",tidyselect::matches("^53-"))%>%
      dplyr::select(1,earliest_date=2) %>%
      tidyr::drop_na() %>%
      dplyr::mutate(earliest_date=lubridate::ymd(.data$earliest_date))

    multi_site_pain <- min_data %>%
      dplyr::select(.data$eid,tidyselect::matches("^6159-0"))

    if (is.character(multi_site_pain$`6159-0.0`)) {
      # Exported RAP data has multi-selection values included as a pipe-separated string
      # rather than the previously expected format with array-elements in separate columns.
      # We assume there are 7 parts as that assumption is made when computing Q1000 below.
      multi_site_pain <- multi_site_pain %>%
        tidyr::separate(
          col = .data$`6159-0.0`,
          sep = "\\|",
          into = paste0("6159-0.", 0:6),
          fill = "right",
          convert = TRUE
        )
    }

    no_pain <- multi_site_pain %>%
      dplyr::filter(.data$`6159-0.0`==-7) %>%
      dplyr::mutate(`6159-0.0`=0) %>%
      dplyr::select("eid",Q1000=`6159-0.0`)

    case_values <- c(1,2,3,4,5,6,7)
    control_values <- c(NA)

    multi_site_pain_filter <- multi_site_pain %>%
      dplyr::filter(!.data$eid %in% no_pain$eid) %>%
      dplyr::mutate(dplyr::across(-.data$eid, dplyr::na_if, -3)) %>%
      dplyr::mutate(dplyr::across(-.data$eid, dplyr::na_if, 8)) %>%
      tidyr::drop_na(.data$`6159-0.0`)
    # now convert all non-na to 1
    multi_site_pain_filtered <- multi_site_pain_filter %>%
      dplyr::mutate(dplyr::across(dplyr::everything(),~replace(.data$., .data$. %in% case_values,1))) %>%
      dplyr::mutate(dplyr::across(dplyr::everything(),~replace(.data$., .data$. %in% control_values,0))) %>%
      dplyr::mutate(Q1000=.data$`6159-0.0`+.data$`6159-0.1`+.data$`6159-0.2`+.data$`6159-0.3`+.data$`6159-0.4`+.data$`6159-0.5`+.data$`6159-0.6`) %>%
      dplyr::select("eid","Q1000") %>%
      dplyr::bind_rows(no_pain) %>%
      dplyr::left_join(age) %>%
      dplyr::left_join(date) %>%
      dplyr::select("eid","Q1000","earliest_date",Q1000_age="age")

    multisite_pain_list <- list(Q1000=multi_site_pain_filtered)
    formula_phenotypes <- append(formula_phenotypes,multisite_pain_list)
  }

  saveRDS(formula_phenotypes,phenotype_save_location)
}
